project:
  type: book
  output-dir: docs

book:
  title: "PrWR 2dH (Schuljahr 25/26)"
  author: "Jacques Mock Schindler"
  
  

  chapters:
    - index.qmd
    - part: "Strafrecht"
      chapters:
        - files/strafrecht/strafe.qmd
        - files/strafrecht/strafen.qmd
        - files/strafrecht/bge120iv265.md
        - files/strafrecht/toetungen.qmd

  downloads: [pdf]
  navbar: 
    right: 
      - icon: github
        href: "https://github.com/SkriptenMk/PrWR_dH_24-27"
        aria-label: GitHub
        target: "_blank"
      - icon: bug
        href: "https://github.com/SkriptenMk/PrWR_dH_24-27/issues"
        aria-label: "Fehler melden"
        target: "_blank"
    search: true

lang: de

format:
  html:
    theme:
      - cosmo
      - brand
    code-download: true
    toc: true
    css: style.css
    code-line-numbers: true
  pdf:
    documentclass: scrreprt
    papersize: a4
    number-sections: true
    toc: true
    top-level-division: chapter
    pdf-engine: xelatex
    crossref:
      chapters: true
    # NEU: Steuerung der Ränder direkt über den Quarto 'geometry'-Schlüssel als String.
    # Dies ist der korrekte Weg, die Option clash zu vermeiden.
    geometry: "tmargin=3cm, bmargin=3cm, lmargin=3cm, rmargin=6cm"
    column-margin-width: 5cm
    header-includes:
      - "\\KOMAoption{captions}{tableheading}"
      - "\\KOMAoption{mpinclude}{true}"
      - "\\setkomafont{disposition}{\\footnotesize\\linespread{0.8}\\selectfont}"
      - "\\setlength{\\marginparpush}{2.5em}"
    # ENTFERNT: Die manuelle \usepackage[...]{geometry} Anweisung, um den Konflikt zu vermeiden.
    block-headings: true
    code-line-numbers: true
    break-at-whitespace: true
