project:
  type: website
  output-dir: docs

website:
  title: "PrWR 2dH (Schuljahr 25/26)"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Strafrecht
        href: files/Strafrecht.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
  pdf:
    pdf-engine: xelatex
    mainfont: Arial
    fontsize: 11pt
    documentclass: article
    classoption: a4paper
    toc: false    



