---
title: "Ziele des Strafrechts und der Strafe"
date: 2025-08-21
date-format: DD.MM.YYYY
author: "Jacques Mock Schindler"
---

## Ziele des Strafrechts

### Fokus des Strafrechts

Das Schweizerische Strafrecht ist Täterorientiert. Es regelt, wie das
Verhalten eines Täters sanktioniert wird. Dabei hält es nicht nur fest,
welche Strafen für welche Delikte verhängt werden, sondern vor allem,
welche Verhaltensweisen überhaupt strafbar sind (vgl.
<a href="https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_1"
target="_blank">
Art. 1 StGB</a>). Das Strafrecht ist damit ein Beispiel dafür, welche
Einschränkungen der Staatsmacht in einem Rechtsstaat auferlegt werden.
<a href="https://de.wikipedia.org/wiki/Franz_von_Liszt" target="_blank">
Franz von Liszt</a>, ein deutscher Jurist des 19. Jahrhunderts, spricht denn
auch vom Strafrecht als der "magna charta des Verbrechers".

### Das Opfer einer Straftat

Im Schweizerischen Strafrecht wird das Opfer einer Straftat lediglich
als Voraussetzung für die Strafbarkeit des Täters betrachtet. Selbst im
Strafprozessrecht kommt dem Opfer nur indirekt Parteistatus zu. Das
Opfer wird grundsätzlich lediglich als Zeuge in den Strafprozess
involviert. Nur über das
<a href="https://www.fedlex.admin.ch/eli/cc/2008/232/de" target="_blank">
Opferhilfegesetz (OHG)
</a> werden Opfer schwerer Straftaten als "Opfer" anerkannt und erhalten
Unterstützung bei der Durchsetzung ihrer Rechte.  
Alle anderen Opfer von Straftaten werden lediglich als Geschädigte
bezeichnet und haben ausschliesslich Anspruch auf zivilrechtlichen
Schadenersatz im Sinne des 
<a
href="https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#part_1/tit_1/chap_2"
target="_blank">
ausservertraglichen Haftpflichtrechts</a>.

## Ziele der Strafe

::: {.callout-important appearance=simple}

### Definition

Strafe bedeutet, jemandem bewusst ein Übel zuzufügen.
:::

Bei vielen Diskussionen über die Ziele des Strafrechts geht die
grundlegende Definition von Strafe vergessen. Bei den folgenden
Überlegungen muss diese Definition jedoch stets im Hinterkopf behalten
werden.

### Die Ziele der Strafe im Überblick

1. **Rache**: Die Strafe soll das begangene Unrecht durch das dem Täter
   zugefügte Übel ausgleichen.
2. **Prävention**: Durch die Androhung und Verhängung von Strafen soll
   zukünftigen Straftaten des Täters (Spezialprävention) und
   potentieller weiterer Täter (Generalprävention) entgegengewirkt werden.
3. **(Re)Sozialisierung**: Die Strafe soll erziehend auf den Täter
   einwirken. Es soll sichergestellt werden, dass der Täter nach
   Verbüssen der Strafe in die Gesellschaft (re)integriert werden und in
   Zukunft ein straffreies Leben führen kann.
4. **Sicherung der Rechtsordnung**: Die Strafe dient dazu, die
   Missachtung der Rechtsordnung zu sanktionieren und ihr so Nachachtung
   zu verleihen.

### Zu den Zielen der Strafe im Einzelnen

#### Rache

Die Rache ist wohl das älteste Ziel der Strafe. So alt, wie dieses Ziel
ist, so alt sind auch die Bemühungen, die Rache nicht ausufern zu
lassen. So stehen bereits im alten Testament die oft falsch verstandenen
Verse "Auge um Auge, Zahn um Zahn, Hand um Hand; Fuss um Fuss,
Brandmal um Brandmal, Wunde um Wunde, Strieme um Strieme. (2. Mose 21,
24-25)".  
Dieses Aufforderung ist keine Aufforderung, begangenes Unrecht maximal
zu vergelten, sondern vielmehr ein Aufruf, die Rache auf das Mass des
begangenen Unrechts zu beschränken. Im frühen Mittelalter wurde die hier
sichtbare Idee weitergeführt und die Begrenzung der Rache weiter
verstärkt. Anstelle einer Vergeltung trat die Idee der Wiedergutmachung.
So wurde die Blutrache durch Geldzahlungen ersetzt. Erhaltene
Rechtstexte aus jener Zeit, wie die 
<a href="https://de.wikipedia.org/wiki/Lex_Salica" target="_blank">
"Lex Salica"</a> beinhalten eigentliche
Preislisten für die Abgeltung getöteter oder verletzter Personen. Die
Entschädigung richtete sich nach dem Status der Personen.

Später wurde die Strafe an das Gemeinwesen übertragen. Die Idee war,
dass nicht mehr der Einzelne sich Gerechtigkeit verschaffen muss,
sondern dass das Gemeinwesen die Aufgabe der Strafverfolgung und
Strafvollstreckung übernimmt. Mit dieser Entwicklung ging zuerst eine
deutliche Verschärfung der Strafen einher. Dies hat wohl vor allem damit
zu tun, dass das Gemeinwesen schwach war und sich mit den exemplarischen
Strafen selber vergewissern musste.Erst in der frühen Neuzeit
setzte wieder eine Mässigung der Strafen ein.

#### Prävention

Prävention ist vor dem Hintergrund des Strafrechts ein anderes Wort für
Abschreckung. Es geht darum, potenzielle Täter von der Begehung von
Straftaten abzuhalten, indem die Konsequenzen eines solchen Handelns
deutlich gemacht werden.

Bei der *spezialpräventiven* Wirkung der Strafe wird versucht, den
einzelnen Täter von weiteren Straftaten abzuhalten. Dies geschieht
durch die Verhängung von Strafen, die so gestaltet sind, dass sie
abschreckend wirken. Bei der *generalpräventiven* Wirkung hingegen geht
es darum, die Allgemeinheit von der Begehung von Straftaten abzuhalten.
Hierbei spielt die öffentliche Wahrnehmung von Strafen eine wichtige
Rolle. Wenn die Bevölkerung die Strafen als angemessen und
wirksam empfindet, kann dies dazu führen, dass potenzielle Täter von
der Begehung von Straftaten absehen.

Es hat sich allerdings gezeigt, dass nicht die Strafe an und für sich
abschreckend wirkt. Viel abschreckender ist die Wahrscheinlichkeit,
erwischt zu werden. Dies gilt zumindest für rationale Täter, die ihre
Handlungen abwägen und die Risiken und Konsequenzen ihres
Handelns berücksichtigen.  
Irrationale Täter dürften sich hingegen weder
von einer Strafe noch von der Wahrscheinlichkeit, erwischt zu werden,
abschrecken lassen.

#### (Re)Sozialisierung

Die (Re)Sozialisierung ist ein weiteres wichtiges Ziel der Strafe. Sie
geht davon aus, dass der Täter soziale Defizite aufweist, welche durch
die Strafe kompensiert werden müssen bzw. können. Das Ziel ist es, dass
sich ein Täter nach dem Verbüssen der Strafe (wieder) in die
Gesellschaft integrieren kann.

Die Idee hinter der (Re)Sozialisierung ist, dass viele Straftaten aus
sozialen Benachteiligungen, fehlender Perspektive oder psychischen
Problemen resultieren. Durch gezielte Unterstützung und Förderung soll
dem Täter die Möglichkeit gegeben werden, seine Lebensumstände zu
verbessern und zukünftig straffrei zu leben. 

Für die (Re)Sozialisierung werden verschiedene Massnahmen, wie zum
Beispiel Therapieangebote, Bildungsmassnahmen oder soziale Trainings
angeboten.

#### Sicherung der Rechtsordnung

Die Sicherung der Rechtsordnung berührt ein zentrales Wesensmerkmal des
Rechts. Recht ist nur, was durch gesellschaftliche Zwangsmassnahmen
durchgesetzt werden kann. Dies bedeutet, dass die Einhaltung von
Rechtsnormen nicht nur auf Freiwilligkeit beruht, sondern auch durch
staatliche Gewalt durchgesetzt werden muss. Die Strafe ist Ausdruck
dieser staatlichen Gewalt.
