---
title: "Strafen und Massnahmen"
date: 2025-08-28
date-format: DD.MM.YYYY
author: "Jacques Mock Schindler"
---

Das Schweizerische Strafrecht unterscheidet zwischen Strafen und
Massnahmen. Strafen sind staatliche Reaktionen auf strafbares Verhalten
und setzen ein Verschulden, das heisst, ein vorwerfbares Verhalten des
Täters voraus. Massnahmen hingegen zielen auf Besserung des Täters und
Schutz der Allgemeinheit ab. Massnahmen sind unabhängig vom Verschulden
des Täters. 

## Strafen

Das StGB kennt Geld- und Freiheitsstrafen.

### Geldstrafe

Die Geldstrafen werden in Geldstrafen in Tagessätzen und Bussen
unterteilt. Bei Verhängung einer Geldstrafe wird die Höhe der Strafe
nicht in Franken, sondern in Tagessätzen festgelegt. Die Anzahl der
Tagessätze richtet sich nach der Schwere des Vergehens und dem
Verschulden des Täters. Der Frankenbetrag eines Tagessatzes wird
individuell festgelegt und berücksichtigt die finanziellen Verhältnisse
des Täters (<a
href="https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_34"
target="_blank">Art. 34 StGB</a>). So will der Gesetzgeber
sicherstellen, dass die Geldstrafe jeden Täter gleich hart trifft.  
Im Gegensatz zu den Geldstrafen in Tagessätzen werden Bussen in fixen
Beträgen in Franken festgelegt.

Geldstrafen können für Verbrechen und Vergehen verhängt werden. Bussen
sind für Übertretungen vorgesehen.

### Freiheitsstrafe

Im Schweizerischen Strafrecht unterscheiden sich die Freiheitsstrafen
lediglich in ihrer Dauer. Die kürzeste Freiheitsstrafe beträgt drei
Tage, die Längste grundsätzlich 20 Jahre. Für einzelne besonders schwere
Straftaten sieht das Gesetz lebenslange Freiheitsstrafen vor. Lebenslang
bedeutet in diesem Fall bis zum Tod des Täters.

Es muss allerdings zwischen Strafurteil und Strafvollzug unterschieden
werden. Im Strafurteil wird die Dauer der Freiheitsstrafe festgelegt. Im
Strafvollzug ist es jedoch möglich, die Strafe unter bestimmten
Voraussetzungen zu verkürzen.

## Massnahmen

Bei der Anordnung von Massnahmen stehen dem Gericht verschiedene
Möglichkeiten zur Verfügung. Diese reichen von ambulanten Therapien
anstelle oder parallel zum Strafvollzug bis hin zu stationären
Massnahmen in psychiatrischen Einrichtungen.

## Bedingter Strafvollzug

Der bedingte Strafvollzug ermöglicht es, eine Freiheitsstrafe unter bestimmten
Voraussetzungen zur Bewährung auszusetzen
<a
href="https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#book_1/part_1/tit_3/chap_1/sec_2/lvl_1"
target="_blank"
>
(vgl. Art. 42 ff. StGB)</a>. Solange sich der Verurteilte während der
Probezeit bewährt, das heisst nicht erneut straffällig wird, wird die
Strafe nicht vollzogen.